### ISSUE TITLE
whats is the problem ??

### ISSUE THREAD

**Issue by KedharnathGoud** [knoldus/Lambda-Arch-Spark#1]
Enter number: 2

[info] Running com.knoldus.kafka.consumer.CassandraKafkaConsumer 
[error] (run-main-0) java.lang.UnsupportedClassVersionError: akka/actor/ActorRef : Unsupported major.minor version 52.0
java.lang.UnsupportedClassVersionError: akka/actor/ActorRef : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2570)
	at java.lang.Class.getMethod0(Class.java:2813)
	at java.lang.Class.getMethod(Class.java:1663)
[trace] Stack trace suppressed: run last compile:run for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) Nonzero exit code: 1

**Comment by knoldernarayan** [comment]
@KedharnathGoud  sorry for delay. as per your exception log i think there is some scala or java sdk version issue.please make sure use java8.if issue is still exists then please let me know.

**Comment by KedharnathGoud** [comment]
its actually worked after adding couple dependencies in build. sbt . i have a testing issue . Even though if i give empty string as a key word its able to stream the followers it is not throwing exception or error saying key word is empty . But u did beautiful job i really liked the project and understanding the lambda arch and implementing with Kafka great job :)

**Comment by knoldernarayan** [comment]
Hi @KedharnathGoud  Thanks for complement.

For your question **i give empty string as a key word its able to stream the followers it is not throwing exception or error saying key word is empty**. 
Actually we have used twitter4j streaming api and there is one field **track** which is basically  use for track all given keyword against live twitter stream so there might be chance to match empty keyword with any empty hash tag or twitter body text . But it is totally depend on twitter4j behaviour .
