### ISSUE TITLE
 java.lang.NoClassDefFoundError: org/apache/spark/streaming/dstream/DStream

### ISSUE THREAD

**Issue by terryBaz** [knoldus/Lambda-Arch-Spark#4]
After configuring every things, then `sbt run` work well with [2]CassandraKafkaConsumer and [3] TwitterStreamApp but for [5]SparkStreamingKafkaConsumer i get this error (also for [1], i got a class loader erro) :
`Multiple main classes detected, select one to run:

 [1] com.knoldus.batch.BatchProcessor
 [2] com.knoldus.kafka.consumer.CassandraKafkaConsumer
 [3] com.knoldus.kafka.producer.TwitterStreamApp
 [4] com.knoldus.serving.AkkaHttpServer
 [5] com.knoldus.speed.SparkStreamingKafkaConsumer

Enter number: 5

[info] Running com.knoldus.speed.SparkStreamingKafkaConsumer
[error] (run-main-0) java.lang.NoClassDefFoundError: org/apache/spark/streaming/dstream/DStream
java.lang.NoClassDefFoundError: org/apache/spark/streaming/dstream/DStream
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.streaming.dstream.DStream
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
[trace] Stack trace suppressed: run last compile:run for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) Nonzero exit code: 1
[error] Total time: 4 s, completed 9 mai 2018 11:47:29`

**Comment by singhalroopal** [comment]
hii,' java.lang.NoClassDefFoundError:' did you find any solution of this error.i am using spark 2.3.1 without sbt.i found this error when running "val stream = TwitterUtils.createStream(ssc, None)" .

**Comment by knoldernarayan** [comment]
Issue has been resolved
